//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::block::Entity as Block;
pub use super::friend::Entity as Friend;
pub use super::group::Entity as Group;
pub use super::group_member::Entity as GroupMember;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
